"""
Script to generate a placeholder master_template.pptx.

Run once:
    cd backend
    python deliverables/generators/create_mock_template.py

This creates backend/deliverables/templates/master_template.pptx.

IMPORTANT: Replace this file with your real IBM/consulting brand template.
The generator only uses slide LAYOUTS from this file — it does NOT copy or
re-use slide content. So your real template only needs to contain properly
named slide layouts; the branding (fonts, colours, backgrounds, logos) is
automatically inherited from the slide master.

Required layout names (case-insensitive match):
  - "Title Slide"           → used for the deck cover
  - "Title and Content"     → used for standard bullet slides
  - "Two Content"           → used for two-column slides
  - "Section Header"        → used for section divider slides

If those layouts are missing, the generator falls back to layout index 0.
"""
from pathlib import Path
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

OUTPUT_PATH = Path(__file__).parent.parent / "templates" / "master_template.pptx"
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

# IBM colours (mock — replace with your brand colours in a real template)
IBM_BLUE = RGBColor(0x05, 0x43, 0xCE)
IBM_DARK = RGBColor(0x16, 0x16, 0x16)
IBM_LIGHT_GREY = RGBColor(0xF4, 0xF4, 0xF4)
IBM_WHITE = RGBColor(0xFF, 0xFF, 0xFF)
IBM_COOL_GREY = RGBColor(0x69, 0x6F, 0x6F)

prs = Presentation()
prs.slide_width = Inches(13.33)
prs.slide_height = Inches(7.5)

slide_master = prs.slide_master

# ------------------------------------------------------------------
# Layout 0 — Title Slide
# ------------------------------------------------------------------
tl = slide_master.slide_layouts[0]

# ------------------------------------------------------------------
# Layout 1 — Title and Content  (bullet slides)
# ------------------------------------------------------------------
tc = slide_master.slide_layouts[1]

# ------------------------------------------------------------------
# Produce 4 demo slides so the template visually makes sense
# when opened in PowerPoint before branding is applied.
# ------------------------------------------------------------------

def _add_cover(prs: Presentation) -> None:
    layout = prs.slide_master.slide_layouts[0]
    slide = prs.slides.add_slide(layout)
    tf = slide.shapes.title
    if tf:
        tf.text = "Client Material"
        tf.text_frame.paragraphs[0].font.size = Pt(40)
        tf.text_frame.paragraphs[0].font.color.rgb = IBM_WHITE
    # Subtitle placeholder (index 1 if present)
    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by CKIP Knowledge Platform"


def _add_section(prs: Presentation, title: str) -> None:
    layouts = {l.name.lower(): l for l in prs.slide_master.slide_layouts}
    layout = layouts.get("section header", prs.slide_master.slide_layouts[2])
    slide = prs.slides.add_slide(layout)
    tf = slide.shapes.title
    if tf:
        tf.text = title
        tf.text_frame.paragraphs[0].font.size = Pt(32)
        tf.text_frame.paragraphs[0].font.color.rgb = IBM_WHITE


def _add_content(prs: Presentation, title: str, bullets: list[str]) -> None:
    layouts = {l.name.lower(): l for l in prs.slide_master.slide_layouts}
    layout = layouts.get("title and content", prs.slide_master.slide_layouts[1])
    slide = prs.slides.add_slide(layout)
    tf = slide.shapes.title
    if tf:
        tf.text = title
    body = slide.placeholders[1] if len(slide.placeholders) > 1 else None
    if body:
        tf2 = body.text_frame
        tf2.clear()
        for i, b in enumerate(bullets):
            p = tf2.paragraphs[0] if i == 0 else tf2.add_paragraph()
            p.text = b
            p.level = 0
            p.font.size = Pt(16)


_add_cover(prs)
_add_section(prs, "Section 1")
_add_content(prs, "Slide Title", ["Bullet point one [Source: Document A]",
                                   "Bullet point two [Source: Document B]",
                                   "Bullet point three"])
_add_content(prs, "Two Column Example", ["Replace with real IBM Asset Kit template"])

prs.save(OUTPUT_PATH)
print(f"Mock template written to: {OUTPUT_PATH}")
print()
print("NEXT STEPS:")
print("  1. Open the file in PowerPoint.")
print("  2. Apply your IBM/consulting brand (fonts, colours, logos).")
print("  3. Save the file back to the same path.")
print("  4. The deliverable generator will use this file as the base for all presentations.")
